name: Spellcheck

on: 
  workflow_call:

permissions:
  contents: read

jobs:
  Spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        wget --no-check-certificate https://raw.githubusercontent.com/Open-Systems-Pharmacology/Workflows/main/Spellcheck/wordlist_osp_global.txt
    - uses: rojopolis/spellcheck-github-actions@0.16.0
