name: 'setup R environment'
description: 'Install R, Packages and necessary dependencies'
author: 'Felix MIL'

inputs:
  install-pksim:
    description: 'Wether to install PK-Sim'
    required: true
    default: 'false'
  pksim-url:
    description: 'The URL of the PK-Sim build archive'
    required: false
    default: 'https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/pk-sim/artifacts/setup.zip?branch=develop&pr=false'
  install-pandoc:
    description: 'Wether to install pandoc'
    required: false
    default: 'false'
  install-rclr:
    description: 'Wether to install rClr'
    required: false
    default: 'false'
  rClr-version:
    description: 'The version of rClr to install'
    required: false
  extra-packages:
    description: |
      Extra packages to install defined as described in
      https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies and
      https://r-lib.github.io/pkgdepends/reference/pkg_refs.html#github-packages-github-'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install PK-Sim
      if: ${{ inputs.install-pksim }}
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/install-PKSIM@main
      with:
        pksim-url: ${{ inputs.pksim-url }}

    - name: Setup Pandoc
      if: ${{ inputs.install-pandoc }}
      uses: r-lib/actions/setup-pandoc@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install package dependencies
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/install-package-deps@main
      with:
        install-rClr: ${{ inputs.install-rclr }}
        rClr-version: ${{ inputs.rClr-version }}
        extra-packages: ${{ inputs.extra-packages }}
