name: 'setup R environment'
description: 'Install R, Packages and necessary dependencies'
author: 'Felix MIL'

inputs:
  install-pksim:
    required: false
    default: true
  pksim-url:
    required: false
  install-pandoc:
    required: false
    default: true
  install-rclr:
    required: false
    default: true
  rClr-version:
    required: false
    default: '0.9.2'
  extra-packages:
    required: false

runs:
  using: "composite"
  steps:
    - name: Install PK-Sim
      if: ${{ inputs.install-pksim }}
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/install-PKSIM@main
      with:
        pksim-url: ${{ inputs.pksim-url }}

    - name: Setup Pandoc
      if: ${{ inputs.install-pandoc }}
      uses: r-lib/actions/setup-pandoc@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install package dependencies
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/install-package-deps@main
      with:
        install-rClr: ${{ inputs.install-rclr }}
        rClr-version: ${{ inputs.rClr-version }}
        extra-packages: ${{ inputs.extra-packages }}
