# Retrieves the latest artifact name and run id from a repository with a matching action and starting with pattern
# The action only considers runs with status="success"
# Use the name and run-id with actions/download-artifact
# Note that runs that produce no artifacts are still considered a success, so use only when every run produces artifacts
# or with repositories that cancel runs when nothing will be produced (like scheduled nightly)

name: Get latest artifact name and run id from a repository

on:
    workflow_call:
     inputs:
      repo-name:
       required: true
       type: string
       description: The repository where the artifact is produced

      action-name:
        required: true
        type: string
        description: The name of the file producing the action

      artifact-pattern:
        required: true
        type: string
        description: A matching pattern that will be tested by 'startsWith'. Will match artifacts that end with build numbers for example if you exclude the build number

     secrets:
      github-token:
        required: true

     outputs:
      artifact-name:
       value: ${{ jobs.get-latest-successful-artifact.outputs.artifact-name }}
       description: The name of the artifact matching the pattern

      run-id:
       value: ${{ jobs.get-latest-successful-artifact.outputs.run-id }}
       description: The id of the run that produced the artifact

jobs:
  get-latest-successful-artifact:
   runs-on: ubuntu-latest
   outputs:
      run-id: ${{ steps.find-artifact.outputs.run-id }}
      artifact-name: ${{ steps.find-artifact.outputs.artifact-name }}
   steps:
     
     # Step 1: Get the latest successful workflow run
     - name: Get Latest Successful Run
       id: get-run
       uses: octokit/request-action@v2.x
       with:
         route: GET /repos/Open-Systems-Pharmacology/${{ inputs.repo-name }}/actions/workflows/${{ inputs.action-name }}/runs?status=success
       env:
         GITHUB_TOKEN: ${{ secrets.github-token }}

     # Step 2: List the artifacts for the latest successful run
     - name: List Artifacts
       id: list-artifacts
       uses: octokit/request-action@v2.x
       with:
         route: GET /repos/Open-Systems-Pharmacology/${{ inputs.repo-name }}/actions/runs/${{ fromJson(steps.get-run.outputs.data).workflow_runs[0].id }}/artifacts
       env:
         GITHUB_TOKEN: ${{ secrets.github-token }}
         
     # Step 3: Filter artifacts by startsWith
     - name: Find Matching Artifact
       id: find-artifact
       run: |
         echo "Artifacts from the run: '${{ steps.list-artifacts.outputs.data }}'"
         ARTIFACT_NAME=$(echo '${{ steps.list-artifacts.outputs.data }}' | jq -r '.artifacts[] | select(.name | startswith("${{ inputs.artifact-pattern }}")) | .name')
         echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
         echo "run-id=${{ fromJson(steps.get-run.outputs.data).workflow_runs[0].id }}" >> $GITHUB_OUTPUT