name: Check Markdown links

on: 
  workflow_call:
    inputs:
      folder-path:
        required: false
        type: string
        default: './'

permissions:
  contents: read
  
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        wget --no-check-certificate https://raw.githubusercontent.com/Open-Systems-Pharmacology/Workflows/main/Config/mlc_config.json
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        check-modified-files-only: ${{ github.event_name == 'pull_request' }}
        config-file: './mlc_config.json'
        folder-path: ${{ inputs.folder-path }}
