on:
  workflow_call:
    inputs:
      install-pksim:
        type: boolean
        default: false
      pksim-url:
        type: string
        default: 'https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/pk-sim/artifacts/setup.zip?branch=develop&pr=false'
      install-pandoc:
        type: boolean
        default: false
      install-rclr:
        type: boolean
        default: false
      rClr-version:
        type: string
        default: '0.9.2'
      extra-packages:
        type: string

name: R-CMD-check-build

jobs:
  R-CMD-check-build:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Setup R Environment
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-R-environment@main
        with:
          install-pksim: ${{ inputs.install-pksim }}
          pksim-url: ${{ inputs.pksim-url }}
          install-pandoc: ${{ inputs.install-pandoc }}
          install-rclr: ${{ inputs.install-rclr }}
          rClr-version: ${{ inputs.rClr-version }}
          extra-packages: ${{ inputs.extra-packages }}

      - name: Check Package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: 'c("--no-manual", "--no-stop-on-test-error")'
          build_args: 'c("--no-manual")'
          error-on: 'c("error")'

      - name: Build package
        if: ${{ success() }}
        run: |
          output_dir <- file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "built_package")
          dir.create(output_dir)
          devtools::build(binary = TRUE, path = output_dir)
        shell: Rscript {0}

      - name: Upload built package
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: built_package
          path: ${{ runner.temp }}/built_package/*.zip
