on:
  workflow_call:
    inputs:
      install-pksim:
        type: boolean
        default: false
      pksim-url:
        type: string
        default: 'https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/pk-sim/artifacts/setup.zip?branch=develop&pr=false'
      install-pandoc:
        type: boolean
        default: false
      install-rclr:
        type: boolean
        default: false
      rClr-version:
        type: string
        default: '0.9.2'
      extra-packages:
        type: string

name: test-pkg-and-coverage

jobs:
  test-pkg-and-coverage:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup R Environment
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-R-environment@main
        with:
          install-pksim: ${{ inputs.install-pksim }}
          pksim-url: ${{ inputs.pksim-url }}
          install-pandoc: ${{ inputs.install-pandoc }}
          install-rclr: ${{ inputs.install-rclr }}
          rClr-version: ${{ inputs.rClr-version }}
          extra-packages: ${{ inputs.extra-packages }}

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
