# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

on:
  workflow_call:
    inputs:
      ignore-renv:
        description: 'Skip renv setup if set to true'
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        required: true

name: Test coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup R environment
        id: setup-r-env
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-r-env@main
        with:
          ignore-renv: ${{ inputs.ignore-renv }}
          extra-packages: covr

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
          files: ./cobertura.xml
          plugins: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
